name: Run tests

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "windows-latest"
          - "macos-latest"
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "pypy-3.10"
        env:
          - py

        include:
          - os: "ubuntu-latest"
            python-version: "3.12"
            env: sqla14
          - os: "ubuntu-latest"
            python-version: "3.12"
            env: sqla20
          - os: "ubuntu-latest"
            python-version: "3.12"
            env: sqla21
          - os: "ubuntu-latest"
            python-version: "3.12"
            env: pep484
          - os: "ubuntu-latest"
            python-version: "3.12"
            env: pep8

      fail-fast: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tox
        run: pip install tox

      - name: Run tests
        run: tox -e ${{ matrix.env }}
